### ISSUE TITLE
运行时显示找不到requests的模块

### ISSUE THREAD

**Issue by GuCheng043** [cwuom/netease-cloud-LV10#1]
Traceback (most recent call last):
  File "e:\wyysj\netease-cloud-LV10-main\netease-cloud-LV10\main.py", line 1, in <module>
    import requests
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'requests'

**Comment by cwuom** [comment]
Windows:
  管理员运行cmd 输入
  pip3 install requests -i https://pypi.tuna.tsinghua.edu.cn/simple
Linux:
  sudo pip3 install requests -i https://pypi.tuna.tsinghua.edu.cn/simple

完成后重启main.py
